// Members-only pages are stored ENCRYPTED in src/content/members/*.json
// (generated by `npm run members` from the private members-src/ folder).
export type MembersPageData = {
  slug: string;
  title: string;
  section: string;
  kdf: { name: 'PBKDF2'; hash: 'SHA-256'; iterations: number; salt: string };
  iv: string;
  data: string;
};

const files = import.meta.glob<{ default: MembersPageData }>('../content/members/*.json', { eager: true });

export function getMembersPages(): MembersPageData[] {
  return Object.values(files).map((m) => m.default);
}
